# Generated by Django 4.0.5 on 2022-06-15 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_title_alter_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='title',
            new_name='work_title',
        ),
    ]
