# Generated by Django 4.0.5 on 2022-06-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_title_profile_work_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='user-default.png', upload_to='project_watch/user_profiles/'),
        ),
    ]
