# Generated by Django 4.0.5 on 2022-06-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_user_alter_rating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to='project_images/'),
        ),
    ]
